# agent/prompts/__init__.py
# Makes agent/prompts a Python package so imports like
# from agent.prompts.v2_structured import SYSTEM_PROMPT, ...
# from agent.prompts.v4_rag import customer_risk_prompt, ...
# resolve correctly
